version: '3.2'

services:

  migrations:
    restart: on-failure
    depends_on:
      - ipld-eth-db
    image: vulcanize/ipld-eth-db:v4.1.4-alpha
    environment:
      DATABASE_USER: "vdbm"
      DATABASE_NAME: "indexer"
      DATABASE_PASSWORD: "password"
      DATABASE_HOSTNAME: "ipld-eth-db"
      DATABASE_PORT: 5432

  ipld-eth-db:
    restart: unless-stopped
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "indexer"
      POSTGRES_PASSWORD: "password"
    volumes:
      - indexer_db_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:15434:5432"
    command: ["postgres", "-c", "log_statement=all"]

  geth:
    restart: unless-stopped
    depends_on:
      - ipld-eth-db
    build:
      context: ./geth
    environment:
      DB_USER: vdbm
      DB_NAME: indexer
      DB_HOST: ipld-eth-db
      DB_PORT: 5432
      DB_PASSWORD: password
    volumes:
      - geth_data:/app/data
    ports:
      - "0.0.0.0:8545:8545"

  ipld-eth-server:
    restart: unless-stopped
    depends_on:
      - ipld-eth-db
    image: vulcanize/ipld-eth-server:v4.0.5-alpha
    environment:
      VDB_COMMAND: "serve"
      ETH_CHAIN_CONFIG: "/tmp/chain.json"
      ETH_SERVER_HTTPPATH: 0.0.0.0:8082
      ETH_SERVER_GRAPHQL: "true"
      ETH_SERVER_GRAPHQLPATH: 0.0.0.0:8083
      DATABASE_USER: "vdbm"
      DATABASE_NAME: indexer
      DATABASE_HOSTNAME: ipld-eth-db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: "password"
      ETH_CHAIN_ID: 41337
      ETH_FORWARD_ETH_CALLS: "false"
      ETH_PROXY_ON_ERROR: "true"
      ETH_HTTP_PATH: "geth:8545"
    volumes:
      - type: bind
        source: ./ipld-eth-server/chain.json
        target: /tmp/chain.json
    ports:
    # RPC
      - "0.0.0.0:8082:8082"
    # GraphQL
      - "0.0.0.0:8083:8083"

volumes:
  indexer_db_data:
  geth_data: