version: '3.2'

services:

  migrations:
    restart: on-failure
    depends_on:
      - ipld-eth-db
    image: vulcanize/ipld-eth-db:v4.1.4-alpha
    environment:
      DATABASE_USER: "vdbm"
      DATABASE_NAME: "indexer"
      DATABASE_PASSWORD: "password"
      DATABASE_HOSTNAME: "ipld-eth-db"
      DATABASE_PORT: 5432

  ipld-eth-db:
    restart: unless-stopped
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "indexer"
      POSTGRES_PASSWORD: "password"
    volumes:
      - indexer_db_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:15434:5432"
    command: ["postgres", "-c", "log_statement=all"]

  geth:
    restart: unless-stopped
    depends_on:
      - ipld-eth-db
    build:
      context: ./geth
    environment:
      DB_USER: vdbm
      DB_NAME: indexer
      DB_HOST: ipld-eth-db
      DB_PORT: 5432
      DB_PASSWORD: password
    volumes:
      - geth_data:/app/data
    ports:
      - "0.0.0.0:8545:8545"

  ipld-eth-server:
    restart: unless-stopped
    depends_on:
      - ipld-eth-db
    image: vulcanize/ipld-eth-server:v4.0.5-alpha
    environment:
      VDB_COMMAND: "serve"
      ETH_CHAIN_CONFIG: "/tmp/chain.json"
      ETH_SERVER_HTTPPATH: 0.0.0.0:8082
      ETH_SERVER_GRAPHQL: "true"
      ETH_SERVER_GRAPHQLPATH: 0.0.0.0:8083
      DATABASE_USER: "vdbm"
      DATABASE_NAME: indexer
      DATABASE_HOSTNAME: ipld-eth-db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: "password"
      ETH_CHAIN_ID: 41337
      ETH_FORWARD_ETH_CALLS: "false"
      ETH_PROXY_ON_ERROR: "true"
      ETH_HTTP_PATH: "geth:8545"
    volumes:
      - type: bind
        source: ./ipld-eth-server/chain.json
        target: /tmp/chain.json
    ports:
    # RPC
      - "0.0.0.0:8082:8082"
    # GraphQL
      - "0.0.0.0:8083:8083"

  eth-statediff-fill-service:
    restart: unless-stopped
    depends_on:
      - ipld-eth-db
    build:
      context: ./eth-statediff-fill-service
    environment:
      DATABASE_USER: "vdbm"
      DATABASE_NAME: "indexer"
      DATABASE_HOSTNAME: "ipld-eth-db"
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: "password"
      ETH_HTTP_PATH: "geth:8545"
      WATCHED_ADDRESS_GAP_FILLER_INTERVAL: 60

  watcher-db:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=vdbm
      - POSTGRES_MULTIPLE_DATABASES=moby-mask-watcher,moby-mask-watcher-job-queue
      - POSTGRES_EXTENSION=moby-mask-watcher-job-queue:pgcrypto
      - POSTGRES_PASSWORD=password
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - watcher_db_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:15432:5432"
    profiles: ["watcher"]

  moby-mask-watcher-server:
    restart: unless-stopped
    depends_on:
      - geth
    build:
      context: ./graph-watcher-ts
      args:
        GIT_TOKEN: $GIT_TOKEN
    image: vulcanize/graph-watcher-ts
    command: ["sh", "-c", "yarn server"]
    volumes:
      - ./graph-watcher-ts/moby-mask-watcher.toml:/app/packages/moby-mask-watcher/environments/local.toml
    ports:
      - "0.0.0.0:3001:3001"
    profiles: ["watcher"]

  moby-mask-watcher-job-runner:
    restart: unless-stopped
    depends_on:
      - moby-mask-watcher-server
    build:
      context: ./graph-watcher-ts
      args:
        GIT_TOKEN: $GIT_TOKEN
    image: vulcanize/graph-watcher-ts
    command: ["sh", "-c", "yarn job-runner"]
    volumes:
      - ./graph-watcher-ts/moby-mask-watcher.toml:/app/packages/moby-mask-watcher/environments/local.toml
    profiles: ["watcher"]

volumes:
  indexer_db_data:
  geth_data:
  watcher_db_data:
